a=input("Enter number 1")
b=input("Enter number 2")
addition=int(a)+int(b)
subtraction=int(a)-int(b)
multiplication=int(a)*int(b)
division=int(a)/int(b)
print("Result of addition is",addition)
print("Result of subtraction is",subtraction)
print("Result of multiplication is",multiplication)
print("Result of division is",division)